version: "3.8"
services:
  nginx:
    image: nginx
    build: requirements/nginx/
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress-data:/var/www/html
      - ./srcs/requirements/nginx/conf:/etc/nginx/conf.d
      - ./certbot-etc:/etc/letsencrypt # Mount for SSL certificates

    networks:
      - inception

  mariadb:
    image: mariadb
    build:
      context: ./requirements/mariadb
    env_file:
      - ../.env
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./srcs/requirements/mariadb/conf:/etc/mysql
    secrets:
      - mysql_root_password
      - mysql_user_password
    networks:
      - inception

  wordpress:
    image: wordpress
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - ../.env
    volumes:
      - wordpress-data:/var/www/wordpress
    depends_on:
      - mariadb
    secrets:
      - mysql_root_password
      - mysql_user_password
      - wp_admin_password
      - wp_user_password
    ports:
      - "9000:9000"
    networks:
      - inception

volumes:
  wordpress-data:

networks:
  inception:
    driver: bridge

secrets:
  mysql_root_password:
    file: ../secrets/mysql_root_password.txt
  mysql_user_password:
    file: ../secrets/mysql_user_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
