version: "3.8"
services:
  nginx:
    image: nginx
    build: requirements/nginx/
    container_name: nginx
    depends_on:
      wordpress:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress-data:/var/www/html
      - ./srcs/requirements/nginx/conf:/etc/nginx/conf.d
      - ./certbot-etc:/etc/letsencrypt # Mount for SSL certificates

    networks:
      - inception

  mariadb:
    image: mariadb
    build: requirements/mariadb/
    container_name: mariadb
    env_file:
      - ../.env
    ports:
      - "3306:3306"
    volumes:
      - ./srcs/data/mysql:/var/lib/mysql
      - ./srcs/requirements/mariadb/conf:/etc/mysql
    secrets:
      - mysql_root_password
      - mysql_user_password
    networks:
      - inception
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "--silent"]
      interval: 7s
      retries: 7
      timeout: 7s
      start_period: 10s
    # restart: unless-stopped

  wordpress:
    image: wordpress
    build: requirements/wordpress/
    container_name: wordpress
    env_file:
      - ../.env
    volumes:
      - wordpress-data:/var/www/wordpress
    secrets:
      - mysql_root_password
      - mysql_user_password
      - wp_admin_password
      - wp_user_password
    ports:
      - "9000:9000"
    networks:
      - inception
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wp", "core", "is-installed", "--allow-root"]
      interval: 10s
      timeout: 10s
      retries: 10

    # restart: unless-stopped

volumes:
  wordpress-data:

networks:
  inception:
    driver: bridge

secrets:
  mysql_root_password:
    file: ../secrets/mysql_root_password.txt
  mysql_user_password:
    file: ../secrets/mysql_user_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
