version: "3.8"
services:
  nginx:
    build: requirements/nginx/
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress-data:/var/www/html
      - ./srcs/requirements/nginx/conf:/etc/nginx/conf.d
      - ./certbot-etc:/etc/letsencrypt # Mount for SSL certificates

    networks:
      - inception

  mariadb:
    build:
      context: ./requirements/mariadb
    env_file:
      - ../.env
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./srcs/requirements/mariadb/conf:/etc/mysql
    networks:
      - inception

volumes:
  wordpress-data:

networks:
  inception:
    driver: bridge
