version: "3.8"
services:
  nginx:
    build: requirements/nginx/
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress-data:/var/www/html
      - ./srcs/requirements/nginx/conf:/etc/nginx/conf.d
      - ./certbot-etc:/etc/letsencrypt # Mount for SSL certificates

    networks:
      - inception

  mariadb:
    build:
      context: ./requirements/mariadb
    env_file:
      - ../.env
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./srcs/requirements/mariadb/conf:/etc/mysql
    networks:
      - inception

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - ../.env
    volumes:
      - wordpress-data:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    secrets:
      - mysql_root_password
      - mysql_user_password
    healthcheck:
      test: ["CMD", "wp", "core", "is-installed", "--allow-root"]
      interval: 10s
      retries: 5
    ports:
      - "9000:9000"

volumes:
  wordpress-data:

networks:
  inception:
    driver: bridge

secrets:
  mysql_root_password:
    external: true
  mysql_user_password:
    external: true
