version: "3.8"
services:
  nginx:
    image: nginx
    build: requirements/nginx/
    container_name: nginx
    depends_on:
      wordpress:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress-data:/var/www/html
      - ./srcs/requirements/nginx/conf:/etc/nginx/conf.d
      - ./certbot-etc:/etc/letsencrypt # Mount for SSL certificates

    networks:
      - inception

  mariadb:
    image: mariadb
    build: ./requirements/mariadb/
    container_name: mariadb
    env_file:
      - ../.env
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    secrets:
      - mysql_root_password
      - mysql_user_password
    networks:
      - inception
    healthcheck:
      # test: ["CMD", "mariadb-admin", "ping", " || exit 1"]
      test: ["CMD-SHELL", "mariadb-admin ping -u root -p$$(cat /run/secrets/mysql_root_password) || exit 1"]
      interval: 10s
      retries: 18
      timeout: 10s
      start_period: 30s
    # restart: unless-stopped

  wordpress:
    image: wordpress
    build: requirements/wordpress/
    container_name: wordpress
    env_file:
      - ../.env
    volumes:
      - ./data/wordpress:/var/www/wordpress
    secrets:
      - mysql_root_password
      - mysql_user_password
      - wp_admin_password
      - wp_user_password
    ports:
      - "9000:9000"
    networks:
      - inception
    depends_on:
      mariadb:
        condition: service_healthy
    # healthcheck:
    #   test: ["CMD-SHELL", "wp core is-installed --allow-root || exit 1"]
    #   interval: 10s # Check every 10 seconds
    #   retries: 20 # Increase retries to give it more time
    #   timeout: 30s # Give each health check more time before it fails
    #   start_period: 60s # Delay the start of the health check to give more time for WordPress to initialize
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wp core is-installed --allow-root --path='/var/www/wordpress' || (echo 'Health check failed' && exit 1)",
        ]
      interval: 10s
      retries: 20
      timeout: 30s
      start_period: 60s
    restart: unless-stopped
  # restart: unless-stopped

volumes:
  wordpress-data:

networks:
  inception:
    driver: bridge

secrets:
  mysql_root_password:
    file: ../secrets/mysql_root_password.txt
  mysql_user_password:
    file: ../secrets/mysql_user_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
