name: Deploy to Droplet

on:
  push:
    branches:
      - main
  workflow_dispatch: # Add this to allow manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Set up SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Deploy to Droplet
      # Deploy to Droplet
      - name: Deploy to Droplet
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }} '
            cd /home/slombard/inception_droplet &&

            # Ensure the secrets directory exists
            mkdir -p ./secrets &&

            # Debug: Check if the secrets directory was created
            if [ ! -d "./secrets" ]; then
              echo "Error: secrets directory was not created!";
              exit 1;
            else
              echo "Secrets directory exists.";
            fi &&

            # Create or update the secret files from GitHub secrets
            echo "${{ secrets.MYSQL_ROOT_PASSWORD }}" > ./secrets/mysql_root_password.txt &&
            echo "${{ secrets.MYSQL_USER_PASSWORD }}" > ./secrets/mysql_user_password.txt &&
            echo "${{ secrets.WP_ADMIN_PASSWORD }}" > ./secrets/wp_admin_password.txt &&
            echo "${{ secrets.WP_USER_PASSWORD }}" > ./secrets/wp_user_password.txt &&

            # Pull the latest code and run the Makefile
            git pull && make re &&

            # Optionally clean up the secret files after they have been used
            rm ./secrets/mysql_root_password.txt &&
            rm ./secrets/mysql_user_password.txt &&
            rm ./secrets/wp_admin_password.txt &&
            rm ./secrets/wp_user_password.txt
          '
