name: Deploy to Droplet

on:
  push:
    branches:
      - main
  workflow_dispatch: # Add this to allow manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment
        run: |
          bash setup.sh
      - name: Check variables
        run: |
          echo "DROPLET_USER=${{ secrets.DROPLET_USER }}"
          echo "DROPLET_IP=${{ secrets.DROPLET_IP }}"
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Droplet
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }} '
            cd /home/slombard/inception_droplet &&
            git pull &&
            make
          '
