name: Deploy to Droplet

on:
  push:
    branches:
      - main
  workflow_dispatch: # Add this to allow manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Set up SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Deploy to Droplet
      - name: Deploy to Droplet
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }} '
            cd /home/slombard/inception_droplet &&
            bash setup_droplet.sh &&
            
            # Remove mysql_root_password secret if it exists
            if docker secret ls | grep -q mysql_root_password; then
              docker secret rm mysql_root_password;
            fi &&
            
            # Remove mysql_user_password secret if it exists
            if docker secret ls | grep -q mysql_user_password; then
              docker secret rm mysql_user_password;
            fi &&

            # Create mysql_root_password secret
            echo "${{ secrets.MYSQL_ROOT_PASSWORD }}" | docker secret create mysql_root_password - &&

            # Create mysql_user_password secret
            echo "${{ secrets.MYSQL_USER_PASSWORD }}" | docker secret create mysql_user_password - &&

            # Pull the latest code and run make
            git pull &&
            make droplet
          '
